AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Layout/LineLength:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Metrics/BlockLength:
  Exclude: ['spec/**/*', 'tasks/**/*']

Metrics/ParameterLists:
  Enabled: false

Style:
  Enabled: false
